# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Polychromatic
email: code@horwell.me
description: >- # this means to ignore newlines until "baseurl:"
  A cross-distro front-end for the OpenRazer project. Polychromatic offers a
  tray applet, a graphical interface, a command line program and
  tools to schedule tasks so you can configure lighting and profiles on
  your GNU/Linux system very simply.

  It's like Razer Synapse, but it does more, is open source and cloud-free.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Common URLs
openrazer_repo: "https://github.com/openrazer/openrazer/"
openrazer_website: "https://openrazer.github.io/"
polychromatic_org: "https://github.com/polychromatic/"
polychromatic_repo: "https://github.com/polychromatic/polychromatic/"
facebook_page: "https://facebook.com/p0lychromatic"
twitter_page: "https://twitter.com/p0lychromatic"
rss_feed: "https://github.com/polychromatic/polychromatic/releases.atom"

# Stylesheets
stylesheets:
    - /assets/lib/bootstrap-grid.min.css
    - /assets/css/polychromatic.css

# Navigation
navigation:
    - text: Features
      url: /about/

    - text: Download
      url: /download/

    - text: Documentation
      url: /docs/
