title: Polychromatic
email: code@horwell.me
description: >-
  A cross-distro front-end for the OpenRazer project. Polychromatic offers a
  tray applet, a graphical interface, a command line program and
  tools to schedule tasks so you can configure lighting and profiles on
  your GNU/Linux system very simply.

  It's a bit like Razer Synapse, but only that it's not.

baseurl: ""
url: "https://polychromatic.app"
source_code_url: "https://github.com/polychromatic/polychromatic-website"

# Build settings
markdown: kramdown
#~ plugins:
#~  - jekyll-feed

# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Common URLs
openrazer_repo: "https://github.com/openrazer/openrazer/"
openrazer_website: "https://openrazer.github.io/"
polychromatic_org: "https://github.com/polychromatic/"
polychromatic_repo: "https://github.com/polychromatic/polychromatic/"
rss_feed: "https://github.com/polychromatic/polychromatic/releases.atom"
twitter: "polychromic_app"

# Stylesheets
stylesheets:
    - /assets/lib/bootstrap-grid.min.css
    - /assets/css/polychromatic.css

# Navigation
navigation:
    - text: Features
      url: /about/

    - text: Download
      url: /download/

    - text: Documentation
      url: /docs/

# Docs
sidebar:
    #~ - id: user
      #~ name: User Guide

    - id: dev
      name: Development

    - id: support
      name: Troubleshooting

    - id: project
      name: Project
